#!/bin/sh
# stub ping for host-side tests of luci-app-ipping.
# Behavior selected with STUB_PING_MODE: ok | iputils | partial | fail | empty

mode="${STUB_PING_MODE:-ok}"
is6=0
host=""
for a in "$@"; do
	[ "$a" = "-6" ] && is6=1
	host="$a"
done

if [ "$is6" = 1 ]; then
	cat <<EOF
64 bytes from $host: icmp_seq=1 ttl=64 time=10.5 ms
64 bytes from $host: icmp_seq=2 ttl=64 time=11.0 ms
64 bytes from $host: icmp_seq=3 ttl=64 time=11.5 ms

--- $host ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
EOF
	exit 0
fi

case "$mode" in
	ok)
		cat <<EOF
PING $host ($host) 56(84) bytes of data.
64 bytes from $host: icmp_seq=1 ttl=118 time=0.123 ms
64 bytes from $host: icmp_seq=2 ttl=118 time=0.145 ms
64 bytes from $host: icmp_seq=3 ttl=118 time=0.167 ms

--- $host ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
EOF
		;;
	iputils)
		cat <<EOF
PING $host ($host) 56(84) bytes of data.
64 bytes from $host: icmp_seq=1 ttl=118 time=0.123 ms
64 bytes from $host: icmp_seq=2 ttl=118 time=0.145 ms
64 bytes from $host: icmp_seq=3 ttl=118 time=0.167 ms

--- $host ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss, time 2003ms
rtt min/avg/max/mdev = 0.123/0.145/0.167/0.017 ms
EOF
		;;
	partial)
		cat <<EOF
PING $host ($host) 56(84) bytes of data.
64 bytes from $host: icmp_seq=1 ttl=118 time=0.5 ms
64 bytes from $host: icmp_seq=3 ttl=118 time=1.0 ms

--- $host ping statistics ---
3 packets transmitted, 2 received, 33% packet loss, time 2003ms
EOF
		;;
	fail)
		cat <<EOF
PING $host ($host) 56(84) bytes of data.

--- $host ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2003ms
EOF
		;;
	empty)
		;;
esac
exit 0
